# Generated by Django 4.0.4 on 2022-06-08 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='usernames',
        ),
    ]
